title: You will never walk alone
author: Xue Shaohua
email: 1155141685@domain.com
description: > # this means to ignore newlines until "baseurl:"
  You will never walk alone!

# social links
twitter_username: chenmo2001 # DO NOT include the @ character, or else the build will fail!
github_username:  XueShaohua # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
